In [2]:
import tensorflow as tf
import numpy as np

In [35]:
# Filter is the block of data (pixels) to scan an image and produce a value
filter_size = [3, 3]

# A grey scale image would have one, RGB would have 3
input_channel = 1

# Number of channels to produce. With data aggregated, each channel 
output_channel = 2

In [50]:
image = [
    [0.11, 0.12, 0.13, 0.14],
    [0.21, 0.22, 0.23, 0.24],
    [0.31, 0.32, 0.33, 0.34],
    [0.41, 0.42, 0.43, 0.44]
]
height = len(image)
width = len(image[0])
print("%d x %d" % (height, width))

4 x 4


In [39]:
X = tf.placeholder(tf.float32, [None, height, width, input_channel])

## Convolutional Weights and Bias
### Weight Shape: 3 x 3 x 1 x 2
    * Filter sizes: 3 x 3 (Modeler's choice)
    * Input Channels: 1 (Greyscale)
    * Output Channels: 2 (Modeler's choice)	

In [40]:
# 3 x 3 filter shape
filter1 = [
    [.4, .6, .4],
    [.6, .9, .6],
    [.1, .6, .4], 
]

# Each filter only has one input channel (grey scale)
# 3 x 3 x 1
channel_filters1 = [filter1]

# We want to output 2 channels which requires another set of 3 x 3 x 1

filter2 = [
    [.9, .5, .9],
    [.5, .3, .5],
    [.9, .5, .9],
]
channel_filters2 = [filter2]

# Initialized Weights
# 3 x 3 x 1 x 2
convolution_layer1 = [channel_filters1, channel_filters2]

print(convolution_layer1[0][0][2][0])

0.1


In [41]:
for filters in convolution_layer1:
    for channel_filter in filters:
        for row in channel_filter:
            print(row)
        print()

[0.4, 0.6, 0.4]
[0.6, 0.9, 0.6]
[0.1, 0.6, 0.4]

[0.9, 0.5, 0.9]
[0.5, 0.3, 0.5]
[0.9, 0.5, 0.9]



### Bias Shape: 2
Matches the number of output channels

In [42]:
biases_1 = [0.1, 0.1]

## Convolutional Layers

In [46]:
# Number of pixels to shift want evaluating a filter
stride_1 = 1

# Transpose to match inputs 
W1 = tf.Variable(np.transpose(convolution_layer1), dtype=tf.float32)
B1 = tf.Variable(biases_1, dtype=tf.float32)
print(W1.shape)

(3, 3, 1, 2)


# Activation Shape: 28 x 28 x 4
* dimension_1 = hight / stride
* dimension_2 = width / stride
* dimension_3 = output_channel

In [ ]:
stride_shape = [1, stride_1, stride_1, 1]
conv_product = tf.nn.conv2d(X, W1, strides=stride_shape, padding='SAME') + B1
Y1 = tf.nn.relu(conv_product)

print(Y1.shape)

(?, 4, 4, 1)


In [28]:
# Create a session
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [29]:
x = sess.run(W1)

# Transpose to match our model 
print(np.transpose(x))

[[[[ 0.4  0.6  0.4]
   [ 0.6  0.9  0.6]
   [ 0.1  0.6  0.4]]]


 [[[ 0.9  0.5  0.9]
   [ 0.5  0.3  0.5]
   [ 0.9  0.5  0.9]]]]


array([[[[ 0.05127421, -0.03921978, -0.06924574],
         [ 0.14473604, -0.13749844,  0.00805295],
         [-0.1016577 ,  0.03831165,  0.09203645]]],


       [[[-0.02428164, -0.06482875,  0.03666113],
         [-0.04038973, -0.01543858,  0.0597358 ],
         [ 0.01271192, -0.17953405,  0.15079948]]]], dtype=float32)