In [1]:
import tensorflow as tf
import numpy as np

In [4]:
input_shape = [3, 5]
input_x = tf.constant(1.0, shape=input_shape)
input_x.shape

TensorShape([Dimension(3), Dimension(5)])

In [5]:
sess = tf.InteractiveSession()
input_x.eval()

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [13]:
y = tf.constant([1., 2., 3., 4., 5.,])
addition = input_x + y
addition.eval()

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  4.,  5.,  6.]], dtype=float32)

In [12]:
y = tf.constant([1., 2., 3., 4., 5.,])
product = input_x * y
product.eval()

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]], dtype=float32)

In [14]:
sess.close()